# Generated by Django 4.2.1 on 2023-05-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TutanakResimVeri",
            fields=[
                (
                    "ysk_no",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ysk_no",
                    ),
                ),
            ],
            options={
                "verbose_name": "tutanak_verisi",
                "verbose_name_plural": "tutanak_verileri",
            },
        ),
        migrations.CreateModel(
            name="Veri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rt_oy", models.IntegerField(verbose_name="rt_oy")),
                ("kk_oy", models.IntegerField(verbose_name="kk_oy")),
                ("toplam_oy", models.IntegerField(verbose_name="toplam_oy")),
                ("gecersiz_oy", models.IntegerField(verbose_name="gecersiz_oy")),
                (
                    "sandik_no",
                    models.CharField(max_length=10, verbose_name="sandik_no"),
                ),
                (
                    "tutanak_veri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_recognizer.tutanakresimveri",
                    ),
                ),
            ],
            options={
                "verbose_name": "tutanak_verisi",
                "verbose_name_plural": "tutanak_verileri",
            },
        ),
        migrations.CreateModel(
            name="TutanakImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_tutanak",
                    models.ImageField(upload_to="", verbose_name="tutanak"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="barcode"
                    ),
                ),
                (
                    "tutanak_veri",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_recognizer.tutanakresimveri",
                    ),
                ),
            ],
            options={
                "verbose_name": "tutanak_resimi",
                "verbose_name_plural": "tutanak_resimleri",
            },
        ),
    ]
