# Generated by Django 4.2.1 on 2023-05-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_recognizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutanakimage",
            options={
                "verbose_name": "Tutanak Resimi",
                "verbose_name_plural": "Tutanak Resimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="tutanakresimveri",
            options={
                "verbose_name": "Tutanak Verisi ve Resimi",
                "verbose_name_plural": "Tutanak Veri ve Resimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="veri",
            options={
                "verbose_name": "Tutanak Verisi",
                "verbose_name_plural": "Tutanak Verileri",
            },
        ),
        migrations.RenameField(
            model_name="tutanakimage",
            old_name="full_tutanak",
            new_name="tutanak",
        ),
    ]
