# Generated by Django 4.2.1 on 2023-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_recognizer", "0002_alter_tutanakimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutanakimage",
            name="tutanak",
            field=models.FileField(upload_to="", verbose_name="tutanak"),
        ),
    ]
