# Generated by Django 4.2.1 on 2023-05-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_recognizer", "0003_alter_tutanakimage_tutanak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutanakimage",
            name="tutanak",
            field=models.TextField(verbose_name="tutanak"),
        ),
    ]
