# Generated by Django 4.2.1 on 2023-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_recognizer", "0005_alter_tutanakimage_tutanak"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutanakimage",
            name="need_to_be_checked",
            field=models.BooleanField(default=False),
        ),
    ]
